
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package main.java.analyzers.syntactic;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int SEMICOLON = 16;
  public static final int ASTERISK = 4;
  public static final int PLUS = 13;
  public static final int DIGIT = 9;
  public static final int SYMBOL = 19;
  public static final int QUESTION_MARK = 14;
  public static final int IDENTIFIER = 10;
  public static final int SEPARATOR = 17;
  public static final int COLON = 5;
  public static final int TILDE = 20;
  public static final int LETTER = 12;
  public static final int STRING = 18;
  public static final int COMMA = 6;
  public static final int EOF = 0;
  public static final int CONCATENATION = 7;
  public static final int CONJ = 8;
  public static final int ALTERNATION = 2;
  public static final int error = 1;
  public static final int ARROW = 3;
  public static final int RIGHT_CURLY_BRACKET = 15;
  public static final int LEFT_CURLY_BRACKET = 11;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ALTERNATION",
  "ARROW",
  "ASTERISK",
  "COLON",
  "COMMA",
  "CONCATENATION",
  "CONJ",
  "DIGIT",
  "IDENTIFIER",
  "LEFT_CURLY_BRACKET",
  "LETTER",
  "PLUS",
  "QUESTION_MARK",
  "RIGHT_CURLY_BRACKET",
  "SEMICOLON",
  "SEPARATOR",
  "STRING",
  "SYMBOL",
  "TILDE"
  };
}

